config/routes.rb
Rails.application.routes.draw do
  get 'pages/contact'
   root "movies#index"
   resources :movies
   resources :actors
   resources :directors
end

app/models/actor.rb
class Actor < ApplicationRecord
 has_many :actor_movies
 has_many :movies, through: :actor_movies
 validates :fullname, presence: true
end

app/models/actor_movie.rb
class ActorMovie < ApplicationRecord
 belongs_to :actor
 belongs_to :movie
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/director.rb
class Director < ApplicationRecord
 has_many :director_movies
 has_many :movies, through: :director_movies
 validates :fullname, presence: true
end

app/models/director_movie.rb
class DirectorMovie < ApplicationRecord
 belongs_to :director
 belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
 has_many :actor_movies
 has_many :actors, through: :actor_movies
 has_one :director_movie
 has_one :director, through: :director_movie

 accepts_nested_attributes_for :director, :actors
 validates :title, presence: true
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
 def index
  @actors = Actor.all
 end

 def new
  @actor = Actor.new
 end

 def create
  @actor = Actor.new(actor_params)

  if @actor.save
   redirect_to @actor, notice: 'Актер успешно создан.'
  else
   render :new
  end
 end

 def show
  @actor = Actor.find(params[:id])
 end

 private

 def actor_params
  params.require(:actor).permit(:fullname)
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController

   def index
  @directors = Director.all
 end

  def new
    @director = Director.new
  end
  def show
  @director = Director.find(params[:id])

  end
  def create
    @director = Director.new(director_params)

    if @director.save
      redirect_to @director, notice: 'Режиссер успешно создан.'
    else
      render :new
    end
  end

  def edit
    @director = Director.find(params[:id])
  end

  def update
    @director = Director.find(params[:id])

    if @director.update(director_params)
      redirect_to @director, notice: 'Режиссер успешно обновлен.'
    else
      render :edit
    end
  end

  def destroy
    @director = Director.find(params[:id])
    @director.destroy

    respond_to do |format|
      format.html { redirect_to directors_url, notice: 'Director was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private

  def director_params
    params.require(:director).permit(:fullname)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
 def index
  @movies = Movie.all
 end

 def show
  @movie = Movie.find(params[:id])
 end

 def new
  @movie = Movie.new
  @movie.build_director
  @movie.actors.build
 end

 def create
  @movie = Movie.new(movie_params)
  if @movie.save
   redirect_to @movie, notice: 'Movie was successfully created.'
  else
   render :new
  end
 end
 private

 def movie_params
  params.require(:movie).permit(:title, :year, :description, :director_id, actor_ids: [], actors_attributes: [:id, :fullname, :_destroy], director_attributes: [:id, :fullname])
 end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/actors/index.html.erb
<h1>Актеры</h1>

<%#= link_to "Режиссера", new_director_path %>

<ul>
  <% @actors.each do |actor| %>
    <li>
      <%= link_to actor.fullname, actor %>
    </li>
  <% end %>
</ul>

app/views/actors/show.html.erb
<h1><%= @actor.fullname %></h1>
<h2>
  <p>
    <strong>Сыграл в фильмах:</strong>
    <% @actor.movies.each do |movie| %>
      <%= movie.title %>.
    <% end %>
  </p>

</h2>

app/views/directors/index.html.erb
<h1>Режиссеры</h1>

<%#= link_to "Режиссера", new_director_path %>

<ul>
  <% @directors.each do |director| %>
    <li>
      <%= link_to director.fullname, director %>
    </li>
  <% end %>
</ul>

app/views/directors/show.html.erb
<h1><%= @directors.fullname %></h1>
<h2>
  <p>
    <strong>Режиссер:</strong>
    <% @directors.movies.each do |movie| %>
      <%= movie.title %>.
    <% end %>
  </p>

</h2>

app/views/layouts/_header.html.erb
<header>
  <div class="logo">Movie Maze</div>
  <nav>
    <ul>
      <li><a href="/">Фильмы</a></li>
      <li><%= link_to 'Режиссер', directors_path %></li>
      <li><%= link_to 'Актеры', actors_path %></li>
      <li><%= link_to 'Добавить фильм', new_movie_path %></li>
      <li><%= link_to 'Контакты', pages_contact_path %></li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieMaze</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render partial: 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: @movie, local: true) do |form| %>
  <!-- Общие поля для фильма -->
  <div>
    <%= form.label :title, 'Название фильма' %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :year, 'Год выпуска' %>
    <%= form.number_field :year %>
  </div>

  <div>
    <%= form.label :description, 'Описание' %>
    <%= form.text_area :description %>
  </div>

  <!-- Поля для режиссера -->
  <div>
    <%= form.fields_for :director do |director_form| %>
      <%= director_form.label :fullname, 'Режиссер фильма' %>
      <%= director_form.text_field :fullname %>
    <% end %>
  </div>

  <!-- Поля для актеров -->
  <div>
    <%= form.fields_for :actors do |actor_form| %>
      <%= actor_form.label :fullname, 'Актер 1' %>
      <%= actor_form.text_field :fullname %>
    <% end %>
  </div>

  <div>
    <%= form.fields_for :actors do |actor_form| %>
      <%= actor_form.label :fullname, 'Актер 2' %>
      <%= actor_form.text_field :fullname %>
    <% end %>
  </div>
  <div>
    <%= form.submit 'Сохранить' %>
  </div>
<% end %>

app/views/movies/index.html.erb
<h1>Фильмы</h1>

<%#= link_to "Добавить фильм", new_movie_path %>

<ul>
  <% @movies.each do |movie| %>
    <li>
      <%= link_to movie.title, movie %> (<%= movie.year %>)
      <p><%= movie.description %></p>
    </li>
  <% end %>
</ul>

app/views/movies/new.html.erb
<h1>Добавить фильм</h1>

<%= render 'form', movie: @movie %>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>

<p>
  <strong>Актеры:</strong>
  <% if @movie.actors.present? %>
    <% @movie.actors.each do |actor| %>
      <%= actor.fullname %>,
    <% end %>
  <% else %>
    Нет информации об актерах для этого фильма.
  <% end %>
</p>


<p>
  <strong>Режиссер:</strong>
  <%= @movie.director.fullname %>
</p>


<p>
  <strong>Год выпуска:</strong> <%= @movie.year %>
</p>

<p>
  <strong>Описание:</strong> <%= @movie.description %>
</p>

app/views/pages/contact.html.erb
<p>Ну ты заходи, если че.....</p>